### ISSUE TITLE
Download status indicator for gallery views

### ISSUE THREAD

**Issue by Simon-Tesla** [Simon-Tesla/RaccoonyWebEx#1]
Show some sort of indicator for whether something has been downloaded or not on the gallery pages. 

This might be implemented by storing a list/hash of page URLs where we've downloaded stuff, and then showing the right icons when rendering out the gallery page. Given that the current download status indicator only works if the download is still shown in the downloads manager (which usually gets cleared once per session), this sort of thing might be useful regardless.

Would need to disable this feature in private browsing mode.

**Comment by anonfurry** [comment]
Question: Is this issue isolated to Firefox Quantum, or does this exist for Chrome as well?

**Comment by Simon-Tesla** [comment]
This is a feature idea that hasn't been implemented yet. The existing download status indicator is definitely cleared when starting a new browsing session on Firefox, but I don't know exactly what the behavior is on Chrome, other than that it seems to be cleared less often.

**Comment by Simon-Tesla** [comment]
This request has been open for a while and to be honest it feels like it'd be more trouble than its worth, given that any indicator we pick would have to be integrated into the gallery view for each site in a way that works for each one without getting in the way of anything that the site has on its own. 

Closing this issue.
