### ISSUE TITLE
FurAffinity plugin no longer DTRT for non-image submissions on old FA UI

### ISSUE THREAD

**Issue by Eupeptic1** [Simon-Tesla/RaccoonyWebEx#100]
The FurAffinity plugin no longer does the right thing for non-image submissions, if the user has selected the old FA UI (FA calls it "classic" mode).  It downloads the generic or artist-provided thumbnail image, rather than the story, music, etc.

**Steps to reproduce**
1.  In your FA account settings, under "Site Layout/Theme", set "Template" to "Classic".
2. Visit a non-image submission.  Make a note of the author and the file type (.txt, .rtf, .mp3, etc) displayed on FA.  Some examples:

https://www.furaffinity.net/view/35116168/  (mp3 audio, custom thumbnail, sfw)
https://www.furaffinity.net/view/6955166/ (mp3 audio, generic thumbnail, sfw)

https://www.furaffinity dot net/view/33190150/ (story, custom thumbnail, nsfw)
https://www.furaffinity.net/view/24404967/ (story, generic thumbnail, sfw)

3.  Mouse over the raccoon head and click "Download".
4.  Look in your `Downloads/raccoony/furaffinity/[author]/` directory.

**Expected behavior**
That directory should contain the correct type of file for the submission: .txt/.rtf/.doc for a story, .mp3/.wav for audio, .swf for Flash, etc.

**Actual behavior**
The directory contains a file ending in .gif.  It may actually be a small 50x50 .gif, if the submission used one of FA's "generic" thumbnails; otherwise it will actually be a PNG or JPEG image with a .gif extension, if the submission used a custom thumbnail provided by the artist.

**Environment**
Raccoony 1.2.4, with  modifications for recent issues
Firefox 78.10.0esr, 64-bit, desktop
Debian Linux 9.9, amd64/x86_64

**Comment by Eupeptic1** [comment]
**Analysis**
The FA plugin currently contains some code that attempts to support both the old and new UI, and I believe this worked at one time.  I don't *think* FA has updated the old UI, but I don't *know* that.

I don't know of any statements in the user-facing documentation that we only support the new UI, but maybe there is one somewhere.

FA's new UI went into production on 2019-12-31, or almost a year and a half ago.  There seems to be a lack of bug reports relating to the old FA UI, so *maybe* it's OK to conclude that not that many people are using it?

I found this by doing automated testing for #85 .  I downloaded submissions under both the old and new UI and diffed the resulting directories, and noticed that the files didn't match.

**Comment by Eupeptic1** [comment]
At some point in the past couple of years, FA changed from using `d.facdn.net` to `d.furaffinity.net` in the URL for the download button.  This may have been just for the old UI, or site-wide; I'm not sure.

The code to handle the old UI specifically looked for `d.facdn.net`, so it couldn't find anything once FA made that change.  I _think_ the existing fall-back code in Raccoony ended up doing the right thing for images, but not for anything else (music, stories, Flash).

I have implemented and tested a fix [here](https://gist.github.com/Eupeptic1/fe9c9946223facdac96b41cc810d453c).

I tested it by downloading my set of 30 test FA submissions under both the new and old UI.  The downloaded images, stories, Flash, etc all compare binary equal.  The downloaded metadata files are almost the same, except for the URLs; the old UI gives you some URLs that have `d.furaffinity.net/download/` in them, where the new UI gives you just `d.furaffinity.net/`.

The previewUrl for Flash submissions in that code is still a little broken; the code looks for a `submissionImg`, which Flash submissions don't have on either old or new UI.

**Comment by Simon-Tesla** [comment]
Sorry for taking so long to get back to you on this one.

This one's complicated enough that I'm not planning to include it in the 1.2.5 bugfix release I'm spinning up; if possible could you please submit this one as a pull request when you have a moment?

**Comment by Eupeptic1** [comment]
The gist I linked [above](https://gist.github.com/Eupeptic1/fe9c9946223facdac96b41cc810d453c) fixes two things at once: #85 and #100 (this issue).

I discovered that my previous fix for issue #85 (which was merged in PR #102) wasn't all the way correct; it broke Flash support for FA.  I noted the problem on #85, and my fix for it.  I wasn't sure if putting comments on a closed bug was the right procedure, but I can't reopen closed bugs, so I figured that was the best spot for it.

If you are OK with both fixes ( #85 and #100 ) waiting until after 1.2.5, then I'll give you a PR for this after 1.2.5 is out.  If you want the fix for #85 to be in 1.2.5, then I can give you something that just fixes #85, and doesn't do anything about #100 .

**Comment by Simon-Tesla** [comment]
Yeah, I think waiting will work out the best for now. I'm not overly concerned about flash content as it's increasingly unlikely a given person will be able to do much with it anyway.

**Comment by Eupeptic1** [comment]
OK. I'll wait until 1.2.5 is out, catch myself up to that, test this fix again, and then give you a PR for it.

**Comment by Eupeptic1** [comment]
I caught myself up to 1.2.5, re-implemented this fix, and did some testing.

Formal test 1 was done under Firefox 78.13.0esr, 64-bit, desktop, on Debian Linux 9.13, 64-bit.
Formal test 2 was done under Chrome 93.0.4577.63, desktop, on Debian Linux 10.10, 64-bit.

(This is the same test environment as the tests I did a couple of days ago on stock 1.2.5.  I was slightly confused about which version of Debian I had on each box when I reported via email after those tests.)

### Formal test 1 (issues #85, #100):

I loaded 1.2.5+this fix into Firefox using about:debugging.

I logged into FA and selected the "new" / "modern" UI.

I ran 1.2.5+this fix on the set of 30 test bookmarks from 2021-08-11.

On FA, I then selected the "old" / "classic" UI.  I cleaned out the download history in Firefox.

I ran 1.2.5+this fix on the set of 30 test bookmarks from 2021-08-11.

I then compared the results in two ways.

#### 1.2.5+this fix, FA new UI, Firefox  *VS*  1.2.5+this fix, FA old UI, Firefox

Both versions downloaded 60 files (30 submission files + 30 metadata files).  All 30 submission files compare binary equal between the two versions.  The metadata files for the 7 image submissions compare binary equal between the two versions.

The metadata files for the 23 non-image submissions vary.

In all 23 of them, the "url" field in the JSON differs; the ones from the old UI start with `d.furaffinity.net/download/art/`, while the ones from the new UI start with `d.furaffinity.net/art/`.  This is an expected difference.

Also, in the three metadata files for the Flash submissions, the "previewUrl" field in the JSON differs in the same way; the ones from the old UI start with `d.furaffinity.net/download/art/`, while the ones from the new UI start with `d.furaffinity.net/art/`.  This is also an expected difference.

This shows that issue #100 is fixed.

#### 1.2.5+this fix, FA new UI, Firefox  *VS*  stock 1.2.5, FA new UI, Firefox

1.2.5+this fix downloaded 60 files.

Stock 1.2.5 downloaded 54 files; it missed the three Flash submissions and their metadata files.

The 54 files that the two versions have in common compare binary equal.

This shows that issue #85 is fixed.

### Formal test 2 (issues #85, #100):

I loaded 1.2.5+this fix into Chrome as an unpacked extension.

I logged into FA and selected the "new" / "modern" UI.

I ran 1.2.5+this fix on the set of 30 test bookmarks from 2021-08-11.

On FA, I then selected the "old" / "classic" UI.  I cleaned out the download history in Chrome.

I ran 1.2.5+this fix on the set of 30 test bookmarks from 2021-08-11.

I then compared the results two ways.

#### 1.2.5+this fix, FA new UI, Chrome  *VS*  1.2.5+this fix, FA old UI, Chrome

Both versions downloaded 60 files (30 submission files + 30 metadata files).  All 30 submission files compare binary equal between the two versions.  The metadata files for the 7 image submissions compare binary equal between the two versions.

The metadata files for the 23 non-image submissions vary.

In all 23 of them, the "url" field in the JSON differs; the ones from the old UI start with `d.furaffinity.net/download/art/`, while the ones from the new UI start with `d.furaffinity.net/art/`.  This is an expected difference.

Also, in the three metadata files for the Flash submissions, the "previewUrl" field in the JSON differs in the same way; the ones from the old UI start with `d.furaffinity.net/download/art/`, while the ones from the new UI start with `d.furaffinity.net/art/`.  This is also an expected difference.

This shows that issue #100 is fixed.

#### 1.2.5+this fix, FA new UI, Chrome  *VS*  stock 1.2.5, FA new UI, Chrome

1.2.5+this fix downloaded 60 files.

Stock 1.2.5 downloaded 54 files; it missed the three Flash submissions and their metadata files.

The 54 files that the two versions have in common compare binary equal.

This shows that issue #85 is fixed.

### Cross comparisons

I did two cross comparisons between the testing today under Firefox and Chrome.

#### 1.2.5+this fix, FA new UI, Firefox  *VS*  1.2.5+this fix, FA new UI, Chrome

Both versions downloaded 60 files (30 submission files + 30 metadata files).  All 60 files compare binary equal between the two versions.

The filenames and directory names were different for three submission files and three metadata files - the ones where artist has a tilde `~` in their FA username.  The ones downloaded under Firefox have tildes in the file and directory names; the ones downloaded under Chrome have underscores instead of tildes.  This is an expected difference.

This shows that issue #85 is fixed.  It also shows that issue #90 is fixed.

#### 1.2.5+this fix, FA old UI, Firefox  *VS*  1.2.5+this fix, FA old UI, Chrome

Both versions downloaded 60 files (30 submission files + 30 metadata files).  All 60 files compare binary equal between the two versions.

The filenames and directory names were different for three submission files and three metadata files - the ones where artist has a tilde `~` in their FA username.  The ones downloaded under Firefox have tildes in the file and directory names; the ones downloaded under Chrome have underscores instead of tildes.  This is an expected difference.

This shows that issue #85 is fixed.  It also shows that issue #90 is fixed.

### Conclusion

I believe the proposed fix is working correctly.  A pull request is imminent.
