### ISSUE TITLE
DeviantArt "Open All in Tab" Duplication on gallery pages

### ISSUE THREAD

**Issue by blob4** [Simon-Tesla/RaccoonyWebEx#103]
**Issue**
DA uses `<a data-hook="deviation_link"...>` twice on gallery pages to link to the art. 
Once for the displayed image and once for the title shown on hover.
Raccoony grabs & opens both links.

**Reproduce**
1. Go to any DA gallery page.
2. Press Hotkey or Click "Open All in Tabs"

**Environment:**
 - Browsers: Chrome & Firefox
 - Latest versions for both
 - Raccoony: v1.2.4

**Screenshot**
![Screenshot 2021-08-01 002246](https://user-images.githubusercontent.com/12388588/127742865-92bdd105-5355-4993-bb3e-e8327dd53b6f.png)

**Additional context**
Links to reproduce on:
 - https://www.deviantart.com/neytirix/gallery/77457502/minty-s-adventure
 - https://www.deviantart.com/silverfox5213/gallery/52549452/league-of-legends

Settings:
[raccoony-settings.txt](https://github.com/Simon-Tesla/RaccoonyWebEx/files/6911322/raccoony-settings.txt)

**Notes**
I looked at the DA plugin and it doesn't look to do anything to negate this.
Though I'm not versed in ts. I'd still assume there's an easy way to filter out duplicates without sorting.

**Comment by Simon-Tesla** [comment]
Confirmed the repro, probably just need to do some work to be more specific about which link we use or manually dedup. Deduping the links in the list might be a generally useful feature for all plugins tho, so it might make sense to implement it as a filtering step in the code that handles opening tabs.

**Comment by Eupeptic1** [comment]
Changing [line 179 of app/plugins/deviantart.ts](https://github.com/Simon-Tesla/RaccoonyWebEx/blob/fbe0e800d6288cf321e48c31b453be927a2e0884/app/plugins/deviantart.ts#L179) to

`let links: HTMLAnchorElement[] = querySelectorAll("[data-hook=deviation_link]:not([aria-label])");`

fixes it for me, at least on the two pages in the original report.  When I do an open-all-in-tabs on either page, I only get six new tabs, each with a unique image.

I am not logged in to DA for this test.  (I don't even have a DA account!)

I haven't tested it against the "old"/"not Eclipse" version of deviantArt.
