### ISSUE TITLE
FurryNetwork plugin fails to find submission ID on some pages

### ISSUE THREAD

**Issue by Eupeptic1** [Simon-Tesla/RaccoonyWebEx#118]
**Quick version:**

If you navigate from one of the "popular" pages to a submission on FurryNetwork, and then download that submission, Raccoony thinks the submission ID is the string "popular", instead of the numeric ID it should be.

**To reproduce:**

1. Go to https://furrynetwork.com/ .
2. Click on "Artwork" at the top of the page, which will load https://furrynetwork.com/artwork/popular/?time=lastWeek .
3. Pick any artwork and click on it.  This will load a page like https://furrynetwork.com/artwork/popular/?page=1&time=lastWeek&viewId=1739445&viewType=artwork (sfw).
4. Note the submission ID in the URL; in this example, `1739445`.
5. Mouse-over the raccoon head and click the "Download" button.  The image will download.
6. On the local filesystem, navigate to where Raccoony saved the file, and look at the filename.

Expected result: Filename will start with the submission ID, like `1739445_Dog_with_arm warmers_by_rhosix9.jpg` .

Actual result: Filename starts with the string "popular", like `popular_Dog_with_arm warmers_by_rhosix9.jpg`.

**Environment:**
Raccoony 1.2.5 + PR #113
Firefox 78.15.0esr, 64-bit, desktop
Debian Linux 10.11, amd64/x86_64, desktop

**Comment by Eupeptic1** [comment]
#### Analysis

The plugin currently expects the URL of individual submissions to look like this:

`https://furrynetwork.com/artwork/[submission-ID]/[title]/ 

This isn't always the case if you landed on a submission from one of the global links at the top of FN (Home, Artwork, Photos, Writing, Multimedia, Community, Commissions), or if you ran a search.  

If you click on the global Artwork link, and then click on an individual submission, you get a URL like

`https://furrynetwork.com/artwork/popular/?page=1&time=lastWeek&viewId=[submission-ID]&viewType=artwork`

Doing a tag search (for `dragon`), and then clicking on a submission in the search results, gets you a URL like

`https://furrynetwork.com/artwork/popular/?page=1&tags[]=dragon&time=lastWeek&viewId=[submission-ID]&viewType=artwork`

The solution is probably to do the current thing (submission-ID as the second thing in the URL path) first, but if that comes up with a submission ID that isn't numbers, then look for the numbers right after `viewID=` in the URL.

**Comment by Eupeptic1** [comment]
I have modified the FurryNetwork plugin.  First, it does the same thing it used to do - split the URL path on `/` and take the second item as the submission ID.  Then, it checks to see if the submission ID is a number.  If it is, fine.  If not, it splits up the full URL on `&` and looks for a piece that contains `viewId=`; if it finds one, it splits that piece on `=` and takes the second piece as the submission ID.

I have tested this on a couple of artwork, photos, and multimedia submissions at FurryNetwork.  Further testing to follow in the next few days.

**Comment by Eupeptic1** [comment]
Tested on more submissions at FN.  I tried it on submissions on the "Most Recent", "Most Popular Last Week", "Most Popular Last Month", and "Most Popular" pages, in the "Artwork", "Photos", and "Multimedia" categories, and it seems to do the right thing.  (Raccoony doesn't currently support stories on FN).

Pull request to be submitted shortly.  I added a little bit of logging around this part of the FN plugin; up to you if you want to keep the logging or not.

Doing an automated test of this will be difficult over long time scales.  Apparently, once the submission falls off the "recently popular" page, FN redirects the "popular" URL to a normal submission URL.  For example, the URL I gave in the initial report 2.5 weeks ago https://furrynetwork.com/artwork/popular/?page=1&time=lastWeek&viewId=1739445&viewType=artwork , now redirects to just https://furrynetwork.com/artwork/1739445/dog-with-arm-warmers/  (sfw), which wouldn't have tickled the original bug.

**Comment by Eupeptic1** [comment]
Apparently this will be part of PR #113 .  https://xkcd.com/1597/ applies.

**Comment by Eupeptic1** [comment]
I'm not sure that the cited commit ( 9ad087cf6777e21574ef9eecc5d577e5857b7539 ) closes this issue.  Or, possibly, I suck at Git.  Or both... :D

The 9ad087c commit contains the extensive changes I made to the FA plugin to handle differences between the old and new UI better.  It also contains a trivial change (whitespace) to the FurryNetwork plugin, but it does **not** contain the changes I made to the FurryNetwork plugin to address this issue.

The pull request I made to fix this issue ( #121 ) is still showing as open for me.  Maybe that is expected, because that PR points at a branch in my repo, and not at the master in my repo.

If you need me to rework that open pull request, or put the fix for this issue on my master, or similar, please let me know.

**Comment by Simon-Tesla** [comment]
Ugh... I think github auto-closes any issue mentioned in the change description which I forgot to look at before submitting. Probably that has a bunch of irrelevant stuff in it too.
