### ISSUE TITLE
Buzzly.art support

### ISSUE THREAD

**Issue by Eupeptic1** [Simon-Tesla/RaccoonyWebEx#126]
[Buzzly.art](https://buzzly.art) is a new site that launched in November 2021.  It might be a good candidate for Raccoony support.

**Comment by Eupeptic1** [comment]
**Technical things:**

Buzzly doesn't seem to use numeric submission IDs for anything.  Everything is based on GUIDs.  If we built a filename for Buzzly in the same way that we currently do for other sites, this artwork (SFW) https://buzzly.art/~rosenasty/art/oh-fr would end up with a filename approximately like `44117fac-d24c-496a-a2ed-6c5d3e129f2b_5ddd4742-b56c-4338-a5a7-b3c5b9436b63_by_rosenasty.png` , which seems a little long and/or not very helpful to end users.  Maybe it would be possible to ship a non-default "Download path" setting for the Buzzly plugin.

The permalinks to individual submissions are only based on the artist's name and the submission title.  This may cause them to point at different artwork in the future, if the artist uploads another submission with the same title. This has already been noted by one of their users on their trouble ticket system: https://buzzly.art/site-tickets/issue/728 

The markup looks somewhat amenable to scraping.  The individual data fields we would want don't always have a unique identifier in the markup; we'd have to look at the plain text to find out if we were on the right element or not.  For instance, the tags, category, and subjects all live in their own `<h4 class="mt-1">`.

I haven't tested this much, but it _might_ be a little bit single-page-app.  Most of the markup lives in a `<div id="app" class="expanded">`.  If you load one page on Buzzly, and click on a link on that page that goes somewhere else on Buzzly, it does enough GET requests that it might be fetching a full new page, instead of rewriting the page you were on.

I know historically we have avoided APIs, but Buzzly has a GraphQL API that it uses internally.  It will give you most of the things you would want to know about a submission, as JSON.  Right now, the API doesn't seem to require a separate authentication step.  There is no public documentation of the API, so it may change.  With GraphQL, you can (apparently always) ask for the current schema the API provides, so you know what is available even without external documentation.

**Nontechnical things:**

Buzzly's "acceptable post" policy seems to be evolving.  A close reading of it from a month or so ago seemed to show that they banned all feral/quadruped characters.  More recently, they made the decision to ban additional subjects.  This may (or may not) affect their ability to attract artists and users.

New user registrations have been closed for about a week, without much explanation as to why, other than a post in their Discord stating that registrations are closed.  See https://buzzly.art/site-tickets/issue/3416 .  (Total speculation on my part, but they might be fighting a spam problem.  The only reason I think that is that Weasyl did the same thing when they had a bad spam problem around 3 years ago.)

**Comment by Simon-Tesla** [comment]
Couple of things:
1. API usage - not wholly opposed to using APIs, but I'd really prefer to avoid having to manage a second login to use one, which is the case for many of the sites with API support. If the site is built more like a single-page app and we can run requests on their API within the page context (and presumably with their cookies) then I'm fine with that.
2. Buzzly.art support - I'll accept a plugin for this if it's contributed, but I have no intention currently on working on support for it myself.

**Comment by Eupeptic1** [comment]
Buzzly registrations will apparently be turned off until the next set of site updates, which are expected "soon".

The full story is apparently in their Discord, which I haven't checked, but it's mentioned in https://buzzly.art/site-tickets/issue/3796 from 18 Feb.

I most likely won't start any work on a plugin until registrations become available again.

**Comment by Eupeptic1** [comment]
Buzzly registrations are still turned off, as of 2022-05-12.  The rate of new submissions there has also slowed dramatically, as of mid-March 2022.

I still don't plan to work on a plugin until registrations become available again.

**Comment by Simon-Tesla** [comment]
Closing this for now. Feel free to reopen if you want to write a plugin.

**Comment by Eupeptic1** [comment]
Some time in the past couple of months, Buzzly opened up new account registrations again.  There's a catch, though - you need an invite code from an existing user.  I haven't pursued obtaining an invite code, so I haven't done any more work on a plugin.  I don't expect that to change until "open" registration is possible again, if ever.
