### ISSUE TITLE
Right click "Download with Raccoony" stopped working 

### ISSUE THREAD

**Issue by Athesis** [Simon-Tesla/RaccoonyWebEx#146]
The right-clock context menu "Download with Raccoony" stopped working 

On right click on any website image and select "Download with Raccoony", nothing happens. Tested it on two different systems and different firefox profiles. 

 - OS: Linux / Windows
 - Browser: Firefox 106.0.2 (64-Bit) (German)
 - Version of Raccoony: 1.2.5 and 1.2.6pre

**Comment by Simon-Tesla** [comment]
That is very strange; it works fine for me. When you say nothing happens, that means you don't see anything new in your downloads? And does it happen for any site you try it on? Would you be willing to share your settings file? (Addons and Themes > Raccoony WebExtension > Options > Export Settings)

**Comment by Athesis** [comment]
Yes, no new download, no file saved. And sure, here's the content of the file (exported from Version 1.2.5 on Linux, the path is  writable):

`{
  "default_settings": {
    "autoFullscreen": true,
    "fullscreenScrollGestureEnabled": false,
    "downloadPath": "Y/NDL/{siteName}/{author}/{submissionId}_{filename}_by_{author}.{extension}",
    "hotkeysEnabled": true,
    "tabLoadDelay": 1,
    "tabLoadSortBy": "date",
    "tabLoadSortAsc": true,
    "tabLoadType": "Timer",
    "writeMetadata": true,
    "autoDownload": false,
    "contextDownloadPath": "Y/mcX/{siteName}/{author}/{filename}.{extension}"
  },
  "e621_settings": {
    "autoFullscreen": false
  },
  "furaffinity_settings": {
    "autoFullscreen": false
  },
  "inkbunny_settings": {
    "autoFullscreen": false
  },
  "patreon_settings": {},
  "version": 4,
  "weasyl_settings": {
    "autoFullscreen": false
  }
}`

Can I open some kind of debug to collect further informations for you?

**Comment by Athesis** [comment]
I might just found the reason, it seems like Raccoony/Firefox dosn't like to save files into a folder with over 13250 Objects?

**Comment by Simon-Tesla** [comment]
I'm not aware of any such limitation for downloads with Firefox. As far as collecting debug logs, if you type in `about:debugging` into the address bar, choose "This Firefox" and then click Inspect on the Raccoony WebExtension, that'll bring up the dev console for the extension. From there, if you can switch to "Console" and look for a log line that starts with `[raccoony] [background] received request messageaction_download` and copy the log with the objects expanded along with any error messages in the log, that would be helpful in figuring out what's going on.

![image](https://user-images.githubusercontent.com/2214046/200098418-5878194e-d758-47cd-ab4b-af61f414098b.png)
![image](https://user-images.githubusercontent.com/2214046/200098558-ac0a0955-9c84-4b4d-bd40-fc03847a2902.png)

**Comment by Simon-Tesla** [comment]
Also, you may need to initiate a download with the console open to see messages about it. I don't think it saves them if the dev tools aren't open.

**Comment by Athesis** [comment]
The problem dosn't reappear as long the debug console is open. As soon I close the Console, it's back again. 

What I did:
Downloads not working.
-> Open the Debug Console
Downloads still not working, nothing happens in the Console.
-> Open Raccoony settings and uncheck / check “Show Raccoony in right-click menu”
Downloads now keep working until I close the Console again. 

Besides the “Background event” warning, noting else seems to happen...

**Comment by Simon-Tesla** [comment]
Hm... weird. This is a long shot, but if you can open the F12 dev tools on the page and look for `[raccoony]` logs there, that might be helpful. If you're not seeing any logs while attempting to download from the background script, it might be that the background script isn't even receiving messages.

**Comment by Simon-Tesla** [comment]
I've noticed that this seems to repro relatively consistently on tumblr. It appears to have something to do with the sites Content Security Policy settings, so I'll have to see if there's a way around that.

**Comment by Simon-Tesla** [comment]
Hmm... this is very strange. I'm starting to see this behavior on other sites too. I suspect but can't confirm that it was introduced by a firefox update. I've noticed that sometimes closing and reopening the tab can fix it, but it doesn't seem universal either.

**Comment by Simon-Tesla** [comment]
The documentation for the [`tabs.executeScript()` API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/executeScript) doesn't mention anything about CSP (and really, there's no reason extension scripts shouldn't be able to run regardless of CSP). Maybe a bug in Firefox? Or maybe I need to specify a [CSP on my extension](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Content_Security_Policy) itself. I'm betting that's likely what's happening here.

**Comment by Simon-Tesla** [comment]
Verified that Chrome seems to work (with version 1.2.5, but the context script mechanism didn't change in 1.2.6pre), so this is either a Firefox change or a Firefox bug.

**Comment by Simon-Tesla** [comment]
Hmm... there's also an issue where the background script doesn't seem to be loading at all in some cases, which is very weird.

**Comment by Simon-Tesla** [comment]
I'll need to do more testing but it looks like changing the manifest to use persistent:true for the background script may fix the issue, at least for now.

**Comment by Simon-Tesla** [comment]
Pretty sure this is the fix; previously (up to v. 105) [Firefox ignored the `persistent: false` key](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/background#browser_compatibility) in the manifest and persisted anyway. There appears to be some sort of bug either in Firefox or in the way I handle event pages that makes it so that non-persistent event pages don't work there, as I've *always* had persistent: false in the manifest and Chrome seemed to behave fine. Guess I'll have to pore over bugzilla, see if I can find anything. Or file one myself. 

I'll give this fix another day or so of testing and then roll another prerelease xpi so that people using FF have an option for this. Might also roll a patch on 1.2.5 in the meantime.

**Comment by Simon-Tesla** [comment]
Fixed in the 1.2.6pre2 and 1.2.5.1 releases.
