### ISSUE TITLE
[Feat. Req] Hentai-Foundry support. 

### ISSUE THREAD

**Issue by momoe** [Simon-Tesla/RaccoonyWebEx#15]
This was initially lumped into another ticket that was closed, so making a seperate one. Please include http://www.hentai-foundry.com support for Racoony's features.

**Comment by momoe** [comment]
Looking at the source code for  H-F images, I see a unique URL used for images being displayed. It seems to follow the pattern of something like "https://pictures.hentai-foundry.com/[a-z]/{author}/{ID}/{filename}.{ext}" 

there's also a uuid int he same html container I believe is reserved for casting votes and what not. 

I'm not sure there's anything unique to parse for Stories submitted on hentai-foundry. The closest I can find is in the html source it has a <div class="boxbody" which contains the whole of each chapter. I hope this helps.

**Comment by Simon-Tesla** [comment]
I've got the bulk of the coding for this plugin done; it should end up in the next release.

**Comment by Simon-Tesla** [comment]
Fixed in 1.2.1
