### ISSUE TITLE
'Open In Tabs' not queuing full list

### ISSUE THREAD

**Issue by momoe** [Simon-Tesla/RaccoonyWebEx#163]
Windows 11, Firefox 117.0 (64-bit). 

I've only tested on Inkbunny, but in my Watch List New Submission page, there are about 60ish submissions per page, but it only loads about 14-30 before stops adding more tabs.

**Comment by Simon-Tesla** [comment]
Which version of Raccoony are you on? I haven't been seeing this on the [1.2.6pre2 release](https://github.com/Simon-Tesla/RaccoonyWebEx/releases/tag/1.2.6pre2).

**Comment by momoe** [comment]
**UPDATE** First; yes I'm on 1.2.6pre2, and I have cleared my browser data, then reinstalled another copy of the XPI. It looks like it's resuming correctly again.

**Comment by Simon-Tesla** [comment]
Ah, ok. Weird. Definitely let me know if you see it crop up again.
