### ISSUE TITLE
[Firefox] Newest Raccoony version (1.31) ignores "Open one tab at a time" setting

### ISSUE THREAD

**Issue by kajoken** [Simon-Tesla/RaccoonyWebEx#171]
**Describe the bug**
After the last update of Raccoony the setting for open tabs doesn't work as expected anymore. "Open one tab at a time" gets forced even though the option is off.

**To Reproduce**
1. Go to https://www.furaffinity.net/
2. Click on "Open all in tabs"
3. See how the tabs are loaded

**bugged behavior**
Each tab opens individually one after another.

**Expected behavior**
After clicking on "Open all in tabs" all tabs open at once.

**Screenshots**
![raccoony-settings](https://github.com/Simon-Tesla/RaccoonyWebEx/assets/72881333/fccc8687-f3e0-4626-8781-d23348e5859f)

**Environment (please complete the following information):**
 - OS: Windows 11 Version 23H2 (OS Build 22631.2861)
 - Browser: Firefox
 - Version of Browser: 121.0
 - Version of Raccoony: 1.3.1

**Additional context**
I only use Raccoony on FurAffinity so no idea if other sites experience the same. I've reset the settings once but that didn't help.

**Comment by zzzzwat** [comment]
I experienced this too.

It seems the placeholder-tab-opening -functionality was removed all the way in 2022: 
https://github.com/Simon-Tesla/RaccoonyWebEx/commit/de7ce7531c253c83543f2fa07143651c98f33dd7

But only now it got released. 

So solution probably is to downgrade the raccoony extension, if one would want to keep the placeholder-tab-opening -action.

**Comment by Simon-Tesla** [comment]
Did I forget to remove that option? Anyway, yes, zzzzwat is correct, I've removed that as the opening all tabs at once mechanism would often leave the browser unusably slow while it opened all those tabs and started the countdown. Doing it this way allows the browser more breathing room and keeps it responsive.

Is there a reason you prefer the open everything at once style?

**Comment by kajoken** [comment]
It's just personal taste. My tabs usually load way faster than the one by one mechanism. So I always have to wait for the tabs to load to save them. Yes I greatly prefer the older version and am thinking of downgrading. Never experienced any Firefox slowdown as well but that may be because I have 32GB of RAM, who knows.

**Comment by Simon-Tesla** [comment]
Fair enough. I'm a little confused by the assertion that the old way is 'faster', though, the target URL doesn't actually start loading until the placeholder tab page has finished counting down, so overall there shouldn't be much of a difference in how long it takes to load everything between the two approaches.

**Comment by Simon-Tesla** [comment]
Heh, can't please everyone, I suppose. I *am* hoping to improve the UI and behavior around open in tabs in the future to allow for greater control over the process, which is part of the motivation for removing the placeholder tabs; they don't really fit well with what I have in mind.

Anyway, thanks for the feedback.

**Comment by kajoken** [comment]
No thank you for such an awesome add-on. It made my furaffinity experience so much better since it has been released. <3
