### ISSUE TITLE
DeviantArt site is not working

### ISSUE THREAD

**Issue by nlboom** [Simon-Tesla/RaccoonyWebEx#174]
DeviantArt site is not working. When you go to the page with the image, the extension window does not appear, the image is not automatically downloaded.

 - OS: Windows 10 22H2
 - Browser: Firefox
 - Version of Browser: 122.0.1
 - Version of Raccoony: 1.3.2
 
https://www.deviantart.com/hinget/art/Battle-Vixen-993512124

**Comment by Simon-Tesla** [comment]
Can confirm. Guess dA changed their DOM, so looks like the plugin needs to be updated.
