### ISSUE TITLE
[E621] “Open all in tabs” option on has disappeared

### ISSUE THREAD

**Issue by nlboom** [Simon-Tesla/RaccoonyWebEx#196]
**Describe the bug**
On E621, the ability to click the “Open all in tabs” button to open all images on a page has disappeared. The pop-up window does not appear. The same is true for the “pools” sections.

![изображение](https://github.com/user-attachments/assets/c50356dd-89f4-4355-a754-36d51e0e51cd)

 - OS: Windows 10
 - Browser: Firefox
 - Version of Browser: 133
 - Version of Raccoony: 142

**Additional context**
Any page with artwork on it: https://e621.net/pools/35873

**Comment by Simon-Tesla** [comment]
Can repro, guessing e6 changed how they do links. Not seeing any errors in the console, the e6 plugin just isn't finding anything.

**Comment by Simon-Tesla** [comment]
Looks like they just changed up the classes a bit, should be an easy fix.
