### ISSUE TITLE
Illegal character subtitution...

### ISSUE THREAD

**Issue by momoe** [Simon-Tesla/RaccoonyWebEx#21]
Didn't know where to file this under bug or feature request but there are some titlesthat Raccony will try to use with the {title} tag that include illegal characters.

For example: $ / : ; \ ? to name a few

I've a seperate userscript that will identify the use of these characters and subtitue them in the file name with Unicode equivilents.

For example

- ":" will be replaced with "：" (U+FF1A)
- ";" to "；" (U+FF1B) 
- "?" to "？" (U+FF1F) 
- "/" to "∕" (U+2215)
- "\\" to "＼" (U+FF3C)
- "*" to"＊" (U+FF0A)
I hope this explains and might resolve some of the other issues with raccoony, like the missing file extensions in other sites.

**Comment by Simon-Tesla** [comment]
I'll take a look. There should be code to sanitize illegal filename characters already, but it's possible that it doesn't catch everything that it should.

**Comment by momoe** [comment]
Perhaps there is, and might be missing a few things, on linux "\" denotes a space in a directory and "/" denotes a subdirectory which it was creating in some cases.

**Comment by Simon-Tesla** [comment]
Yeah, `sanitizePath` in `download.ts` should be catching this. Could you provide a few examples where it's not?

**Comment by momoe** [comment]
Sure: 
https://www.deviantart.com/parororo/art/The-Crawling-City-27-part-1-2-670070704
with {title} in the naming structure will create "The-Crawling-City-27-part-1" then a subdir of "./2-670070704.png"

**Comment by Simon-Tesla** [comment]
Ah, so I'm a little bit of an idiot and forgot to escape the `/` characters out of the variables I pass into the path generation code. Should be fixed in the next revision.

**Comment by Simon-Tesla** [comment]
Fixed in 1.2.1
