### ISSUE TITLE
[Feat. Req] Add to queued? 

### ISSUE THREAD

**Issue by momoe** [Simon-Tesla/RaccoonyWebEx#28]
so as it stands now when you choose to 'open all in tabs' on a page with n-secs for your preferences. those tabs will initiate a countdown adding +n-seconds to each tab. However when you continue to another page and repeat the sequence while that's running all the new tabs will start at 1+n-sec. 

Instead I think it'd be useful; if possible, to add the newly opened tabs to whatever the last tab's running count. This way you prevent having multiple tabs vying to load at the same time. 

I hope I've explained this correctly. I can try to clarify if not.

**Comment by Simon-Tesla** [comment]
Do you mean that if multiple "Open Alls" are started, the next batch starts with a delay higher than the previous batch's maximum delay? That might be a bit tricky; I don't keep track of a batch of tabs when they are opened, I just tell Firefox to open N tabs with the delay page and a specific delay, and the delay page does the work of loading stuff. 

I've actually been meaning to do something to address Open All's performance issues when opening a lot of tabs (at least on my copy of FF), however. I'm thinking I'll probably implement something where we open one tab at a time, and the next tab gets created only after the previous tab starts loading the actual page. I might add some logic to keep track of unfinished batches of tabs while I'm at it, though I'll have to see.

**Comment by momoe** [comment]
Yes, I think having either some way to grab the current number of seconds of delay from the last tab and starting there with the continuation of the next "Open All in Tabs" if there's any currently running. 

However if you're planning on doing some rework. I might want to point you towards this addon, and see if  you can grok at any of the code to make "Lazy load" tabs an alternative to a static countdown. Instead you can choose a number of tabs to be running and the rest will be held in a queue list until one slot opens up and the next in the queue will open.

Take a look and see if this is something you might find useful. 

https://addons.mozilla.org/en-US/firefox/addon/load-background-tabs-lazily/
