### ISSUE TITLE
On mobile Firefox, clicking "open all in tabs" from a private tab opens submissions in non-private tabs

### ISSUE THREAD

**Issue by Eupeptic1** [Simon-Tesla/RaccoonyWebEx#29]
The quick version is that I was using Firefox and Raccoony on Android.  I had FurAffinity open in a private tab.  When I clicked "open all in tabs" in Raccoony, it looked at first like nothing happened... I didn't get any new tabs in the private Firefox window.  When I switched back to the window with the non-private tabs, though, I found the FA submissions had opened in new tabs there.

This wasn't what I expected; I thought that if I clicked "open all in tabs" from a private tab, then Racoony would open the new tabs as private tabs as well.

Steps to reproduce:

1.  Start Firefox.  Open at least one non-private tab; this can even be the empty tab you get when you touch "new tab".

2.  From the three-dots menu in Firefox, select "New Private Tab".

3.  In the new private tab, navigate to an image gallery on a Raccoony-supported site.  You will get the raccoon-head overlay at the bottom left of the screen; that is OK.

4.  Touch the raccoon head to display the "Open all in tabs" button, then touch the "Open all in tabs" button.

5.  Observe no new private tabs opening.  (Expected result: a new private tab opens for each submission on the gallery page.)

6.  From the three-dots menu in Firefox, select "New Tab", to switch back to the Firefox window with non-private tabs.

7.  Observe that this window has new non-private tabs for the submissions on the gallery page.  (Expected result: no new tabs should have appeared on this window.)

I have seen this happening with at least FurAffinity and Shorpy.  I *suspect* it will happen for all sites Raccoony supports.  It happens with the tablet held in both landscape and portrait orientations.

This is with Raccoony 1.2.1 and Firefox 64.0.1, on Android 5.1, ARM A8, tablet.  I feel like I have a fairly vanilla configuration for Firefox; I haven't been playing in about:config very much.  I do also have uBlock Origin 1.17.4 and the Cisco OpenH264 video codec 1.7.1 plugins in Firefox.

I haven't tried it on mobile with newer or older versions of Firefox.

On desktop, I don't see this bug.  If I do a Raccoony "open all in tabs" from a private tab, the new tabs it opens are also private.  I don't normally use Raccoony from a private tab on desktop, but I tried it for this report and it worked correctly.

**Comment by Eupeptic1** [comment]
This recent change https://github.com/Simon-Tesla/RaccoonyWebEx/pull/59 _might_ fix this.  I can't test it right now, but I will try it on mobile Firefox in the next couple of days.

**Comment by Eupeptic1** [comment]
This is still happening with Raccoony 1.2.3.  My Firefox is slightly newer than the original report, at 68.5.0.  Same symptoms as before: open a gallery page on a Raccoony-supported site in a private tab, touch "open in tabs" in Raccoony, and the new tabs open in Firefox - but in the non-private window.

I also tried updating Firefox to the latest version, which is currently 68.7.0, and I still see this happening.

Also with Firefox 68.7.0, I tried turning uBlock Origin off to see if that made any difference, but it does not.

Somewhere in the past year or so, I remember *desktop* Firefox getting more specific about allowing add-ons to run in private tabs.  I don't think this change has percolated to mobile Firefox yet, or if it has, I can't find the knob in the Firefox settings to change it.

Overall, this problem is not a big deal for me, because I don't use mobile Firefox to browse Raccoony-supported sites very often.  I just thought it was worth retesting after the change for #59 was implemented.

**Comment by Eupeptic1** [comment]
Thinking out loud:

The whole `browser.windows` API is unavailable on mobile Firefox.  :(  See the bottom of  https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/windows .

There *is* a `browser.tabs` API, and some of it works on mobile Firefox; see the bottom of
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs .  `tabs.get()` and `tabs.getCurrent()` give you a struct with details of the current tab; it has a boolean for incognito or not.

Not sure yet how to *create* a new incognito tab, though.  Still looking.

**Comment by Simon-Tesla** [comment]
Mozilla's going to be reworking a bunch of stuff on FF Mobile in the near future so I'm probably not going to invest much time there until that lands and they start accepting extensions for it.

In any case, if browser.window.create() isn't available, it doesn't look like this is fixable with the current extension API surface.

**Comment by Eupeptic1** [comment]
Go go gadget USB debugging!

Update: `tabs.getCurrent()` *does not work* from a background script like Raccoony.  Oh well.

You can do a kind of convoluted thing with `tabs.query()`, as shown here, https://stackoverflow.com/a/45535189 , and that *does* give you the tab information.  (I left out the WINDOW_ID_CURRENT in the query spec, because as far as I can tell, it doesn't exist on mobile.)

If you do that, there *is* a `windowId` associated with each tab... but it's the same number whether you have a public or private tab.  :(  (FWIW, it's 3 for me, in both cases.)

The `incognito` property *is* set correctly, according to the tab type - true for a private tab, false for a public tab.

*googling intensifies*

Yeah, we might be screwed.  https://bugzilla.mozilla.org/show_bug.cgi?id=1372178 explains why.  https://bugzilla.mozilla.org/show_bug.cgi?id=1404014 is about adding enough of the `browser.window` API to mobile Firefox to *maybe* make this work, but the one proposed patch only supports some of the "informational" part of the API; it doesn't have `create()`.

I'm looking at the tabs API, seeing if there is any clever way to back into this (successor tabs?  duplicating a tab we know to be private and then changing what's in it?) and *none* of the relevant calls seem to even be available on mobile.

I have one more clever idea that I want to try and report.  Otherwise, this might have to be wontfix until Mozilla does something different.

**Comment by Eupeptic1** [comment]
Clever idea did not work.

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/create says you can supply an optional index to `tabs.create()`, and that

> The provided value will be clamped to between zero and the number of tabs in the window.

This turns out to be a lie.  :D

I thought that *maybe* if we provided a comically large number here, the advertised clamping would take place, and the new tab would be the last one on the stack... which *might* make it show up in the private window?  Kind of hacky, I know.

It turns out that all it does is crash Firefox.  :rofl:   I tried both index = 999 and index = 99, and it crashes as soon as Raccoony tries to create the new tab.

Oh well.  I should have Googled first.  At least now I know more about how to debug on mobile, so maybe a small win.

**Comment by Simon-Tesla** [comment]
closing this issue, as mobile FF is kinda moot at the moment
