### ISSUE TITLE
Weasyl plugin: maybe check for missing submission title and work around it?

### ISSUE THREAD

**Issue by Eupeptic1** [Simon-Tesla/RaccoonyWebEx#32]
I used Raccoony to download a submission from Weasyl whose title only consisted of punctuation.  The downloaded filename didn't have a title in it - just the submission number and the artist's name - and that is not what I expected.  I expected the title to be in the filename as well.

The submission in question is https://www.weasyl.com/~rowdyo/submissions/1527671/ .  (Note: this submission shows a character with blood on his nose/face.)

To reproduce:

1.  With Raccoony installed in a browser, visit the above link.  The raccoon head should appear.

2.  Click the raccoon head, then click the "Download" button.  The submission should download.

3.  In your OS file manager, navigate to the directory where Raccoony saved the file - probably something like ~/Downloads/raccoony/weasyl/rowdyo .

4.  Observe a filename of "1527671_rowdyo-_by_rowdyo.png".  The expected filename would be "1527671_rowdyo-#@*%_by_rowdyo.png".

Discussion:

This may be a Weasyl bug, rather than a Raccoony bug.  The native "download" link that Weasyl provides for this file is also missing the title; if you click it, you get a file named just "rowdyo-.png".  Since the Weasyl plugin derives the title of the submission from that link, it comes up empty when looking for the title.

Raccoony _does_ correctly find the title elsewhere on the page (from the _detail-title_ element); you can see this if you enable saving the metadata file in Raccoony and download the file again.  It will have the line `"title": "#@*% by Rowdy-O",` in the JSON data.

The possible change to Raccoony would be to detect when the title is missing from the Weasyl download link, and to then try to parse the title from elsewhere on the page.

Software used:

Raccoony 1.2.1
Firefox 60.4.0esr (desktop)
Debian 9, 64-bit AMD

**Comment by Simon-Tesla** [comment]
What is the Download URL setting you're using for Weasyl? The default is:
`raccoony/{siteName}/{author}/{submissionId}_{filename}_by_{author}.{extension}`, and the filename is being scraped correctly from the Weasyl webpage you put in the bug, so the behavior is expected. If you want to use the title instead, you can replace `{filename}` with `{title}` in the path you use.

**Comment by Eupeptic1** [comment]
> What is the Download URL setting you're using for Weasyl?

I am using the global default,  `raccoony/{siteName}/{author}/{submissionId}_{filename}_by_{author}.{extension}`  .

> If you want to use the title instead, you can replace `{filename}` with `{title}` in the path you use.

When I do that, I get `1527671_#@___by_Rowdy-O_by_rowdyo.png`, which is better, but also a little redundant.  Simplifying the Download URL to `raccoony/{siteName}/{author}/{submissionId}_{filename}.{extension}` gets me `1527671_#@___by_Rowdy-O.png`, which I guess is as close as I can get.

(As far as I know, * and % are both legal in filenames on ext2/3/4.  Dunno about legacy systems.  :D )

**Comment by Simon-Tesla** [comment]
Raccoony does some sanitization of characters that are invalid in most filesystems, so that behavior is expected. I suppose it's probably unnecessary and that the browser should do the appropriate filtering of such characters, but I tend to get itchy about writing arbitrary filenames to disk.
