### ISSUE TITLE
DA still broken

### ISSUE THREAD

**Issue by Osprey-Hawk** [Simon-Tesla/RaccoonyWebEx#36]
I am still unable to download reliably on DA.  None of the placeholders work properly for standard downloading.  Even the {extension} one doesn't work.  It just plops in DA's useless code instead.  Happens for downloadable and non-downloadable images.

Using the Mouse Menu [default] works for non-downloadable images, but it doesn't save to the artist's folder.  Instead, it saves to Raccoony's base folder even though there is a clear indication of destination on the path.  I've also tried changing the default placeholder to {siteFilename}, but it doesn't work.
![error](https://user-images.githubusercontent.com/45588123/55524945-a8c16900-5654-11e9-8ddf-0c45af2d8681.JPG)

**Comment by momoe** [comment]
Yes, dA has a weird token system that's making downloads and compiling the title name into the file name/extension a bit difficult. 

dA is just really, fickle how they run things. Almost google level of creepy tracking.

**Comment by Simon-Tesla** [comment]
Could you please add some URLs to pictures you're having trouble downloading, as well as whether you're logged-in or not when attempting to download?

**Comment by Osprey-Hawk** [comment]
https://www.deviantart.com/mythkaz/art/2019JUL04A-Ready-to-cosplay-804344086
https://www.deviantart.com/cervelet/art/AS-Beach-Body-9-804342554
https://www.deviantart.com/inkit89/art/Contemplating-Wolf-Edtion-804212238
https://www.deviantart.com/serisabibi/art/Alice-and-Wicked-Queen-2-804334492

As of testing links, some posts without downloads worked without issue.  Namely this one https://www.deviantart.com/omegasunburst/art/Late-night-dip-804352589

**Comment by nikonraccoon** [comment]
I have a similar DA issue, but it appears to be an issue with the file extension  for me. Not sure if this is a separate issue.

https://www.deviantart.com/petuniabubbles/art/Patreon-Request-Neon-Dragon-758228999
Hitting download, I get a file named:
Petuniabubbles_Patreon_Request_- Neon Dragon.4gQ37O_WUgMJbNYs2U6uuVMnLZ83VPvc76SSU8UMM3s

![raccoony_da_issue_1](https://user-images.githubusercontent.com/53057168/61479633-3bff7f80-a962-11e9-9467-76b3820cd388.png)

The file data is all there correctly, just with an incorrect extension. As you can see, irfanview can preview the image. 
![raccoony_da_issue_2](https://user-images.githubusercontent.com/53057168/61479733-6f420e80-a962-11e9-8191-aa3b584b3507.png)

When you try to open it, it tosses up an error, and asks if you want to correct the file extension. 
![raccoony_da_issue_3](https://user-images.githubusercontent.com/53057168/61479752-79fca380-a962-11e9-982d-8ea1d7a6122f.png)

After that, the file is fixed.
