### ISSUE TITLE
Site redesign at shorpy.com breaks Shorpy plugin a little

### ISSUE THREAD

**Issue by Eupeptic1** [Simon-Tesla/RaccoonyWebEx#37]
**What is broken:**
In spring 2019, Shorpy.com redesigned their site.  The existing Shorpy plugin mostly works OK with the redesigned site, but in one case, the metadata file that the plugin can generate ends up with extra text in the "Tags:" line.

Shorpy has two kinds of pages where images are displayed.  One kind just has the large version of the picture and a caption.  The other kind has a smaller version of the picture, comments from users, links to ads, etc.  If you turn on the metadata file download, and download an image from the page with the smaller version of the picture, some of the metadata is not parsed correctly.

**What didn't break:**
"Open all in tabs" still works.
Downloading images from either the full-sized image page or the smaller image page both work.
If you turn on the metadata file download, and download an image from a full-sized image page, the entries in the metadata file are correct.

**Steps to reproduce:**
1.  Navigate to Shorpy.com.
2.  Mouse over the raccoon head and click the gear icon.  Set "save metadata file" to "on", and save changes.
3.  Mouse over the raccoon head again and click "Open all in tabs".  You will get several new tabs with full-sized images in them; that is OK.
4.  Select one of the new tabs with a full-sized image.
5.  Click on the full-sized image to go to the page with the smaller version of that image, comments from users, etc.
6.  Mouse over the raccoon head again and click "Download".  Raccoony will download the image; that is OK.
7.  Using your favorite text editor/viewer, navigate to the directory on your local filesystem where the metadata text files are stored (probably ~/Downloads/raccoony/shorpy/Shorpy ).  Open the metadata file that was just generated.
8.  The metadata file will have a "Tags:" entry with several tags, but also some extraneous text as a tag.  This extra text is not expected - you expect to see a fairly concise list of tags.

For one photo ( https://www.shorpy.com/node/24877 ), what you currently get in the metadata file is

Tags:	The Gallery, A. Rothstein, Frontier Life, Horses, Stores & Markets, 1940 | Shorpy Old Photos | Vintage Photography

but what you would expect to get is just

Tags:	The Gallery, A. Rothstein, Frontier Life, Horses, Stores & Markets, 1940

**Environment**
Raccoony WebExtension 1.2.2
Firefox 60.7.0esr, 64-bit, desktop
Debian Linux 9.9, 64-bit

**Comment by Eupeptic1** [comment]
**Initial analysis**

The plugin parses the HTML <title> tag to find the year of the photo.  The plugin then adds the year to the tag list.

On a full-sized image page, there are no other tags provided on the page, so the year ends up as the only tag in the metadata file.  The format of the HTML <title> didn't change for the full-sized image page, so parsing the year still works right.

On a smaller image page, there are additional tags provided on the page, so the year ends up as the last tag in the list.  The format of the HTML <title> for these pages has changed, though, from

<title>[title]: [year] | Shorpy | #1 Old Photos</title>

to

<title>[title]: [year] | Shorpy Old Photos | Vintage Photography</title>

The plugin was snipping that "constant" text off of the end of the title tag to extract the year... and the constant changed.  So, the plugin still gets the year, but also all of the text that follows it.  This gets added to the metadata file when the plugin attempts to add the year to the list of tags.

**Probable solution**
Change the plugin to either snip off the new "constant" text, or make it a little smarter and have it pluck the year out from between the colon and the first pipe character.  This is in work now.

**Comment by Eupeptic1** [comment]
Patch available, as the above commit shows.

Tested in the same environment as on the original report, and fixes the issue - the extra text no longer appears in the "Tags:" line in the metadata file, when an image is downloaded from the page at Shorpy with the small version of the image.

**Comment by Simon-Tesla** [comment]
It looks like you created the pull-request against your fork? I can't seem to approve/merge it in.

**Comment by Eupeptic1** [comment]
> It looks like you created the pull-request against your fork?

Yes, that's true.

I initially tried to upload the changes to your main version of the repo, but Github told me I didn't have permission to do that, and offered to fork it for me, so I did that.

Once I had my fork, I could not figure out how to create a pull request against your main version of the repo.  I don't know whether that's because I don't have appropriate permissions on your repo, or because I don't know how to use Git/Github.  Possibly it is a combination of both of those issues.

**Comment by Simon-Tesla** [comment]
Ah, apparently there's a "compare against forks" link that lets you do that. Not sure if I'm the only one that can do that or not, but I've created a PR against your changes (linked above). Thanks for the patch, I'll merge this in.

**Comment by Eupeptic1** [comment]
There is no additional work needed - mostly this comment is here so I can remember how to do this again if the need arises.  :)

Based on your comment, I went to the "compare against forks" link at https://github.com/Eupeptic1/RaccoonyWebEx/compare .  That bamfs me to https://github.com/Simon-Tesla/RaccoonyWebEx/compare/master...Eupeptic1:master , and also lets me select a base and a head repository to compare.  I told it that base is "Simon-Tesla/RaccoonyWebEx master" and head is "Eupeptic1/RaccoonyWebEx Eupeptic1-shorpy".  That produced a diff for shorpy.ts and a "create pull request" button.

I didn't click that button, since you already incorporated the change, but I think maybe *that* pull request button would have done what I wanted: create a pull request *from* my version *to* your version.
