### ISSUE TITLE
deviantart Eclipse

### ISSUE THREAD

**Issue by lolirider** [Simon-Tesla/RaccoonyWebEx#39]
daviantart's new Eclipse theme is out now and raccoony doesn't work on all pages

**Comment by Simon-Tesla** [comment]
Yeah, looks like eclipse changed a bunch of stuff around. For now, if you can switch back to the old theme, Raccoony should work okay there. 

As soon as work doesn't drain me of all my energy and will, I'll start looking into these issues.

**Comment by Simon-Tesla** [comment]
Looking into this one now

**Comment by Simon-Tesla** [comment]
Looks like the old theme isn't saving the file with the correct extension either.
