### ISSUE TITLE
Suggested addition to the "Contributing code" section of CONTRIBUTING.md

### ISSUE THREAD

**Issue by Eupeptic1** [Simon-Tesla/RaccoonyWebEx#43]
This is a suggested addition to the "Contributing code" section of CONTRIBUTING.md.

---

**Adding support for a new site - the basics**

You need to write a new Raccoony plugin for that site.  The new plugin has to scrape the HTML for the new site, extract links and metadata from the HTML, and provide them to the rest of Raccoony in a standardized way.

Your plugin needs to provide three main functions: `getMedia()`, `getPageLinkList()`, and `isSubmissionPage()`.

`getMedia()`'s job is to scrape the HTML for one single submission.  It is looking for things like the title of the artwork, the name of the artist, the description and tags the artist provided, and URLs for the full-sized artwork and the preview or thumbnail (if the submission has one).  If it finds everything, it fills in an `I.Media` struct, and returns that to the caller.  If it has a problem, and wants to give up scraping and go home, it can return null to the caller.

`getPageLinkList()`'s job is to scrape the HTML for a "gallery", "latest submissions", or "favorites" page.  It is looking for one or more links to submissions.  It adds those links to an `I.PageLinkList` struct, and returns that to the caller.

`isSubmissionPage()`'s job is to provide a simple yes-or-no answer as to whether a particular URL is a submission page or not.  Most sites have a consistent URL format for this - something like https://www.example.com/submissions/123456 or https://www.example.com/gallery/view/678910 .  You can look for the "/submissions/" or "/gallery/view/" respectively to make this decision.

The code for the new plugin goes in the `app/plugins` directory; if you're targeting yoyodyne.com, a good name is probably `yoyodyne.ts`.

To tie the new plugin into the rest of Raccoony, you also need to edit three other files: `app/page_inject.tsx`, `app/plugins/index.ts`, and `manifest/manifest.json`.

In `page_inject.tsx`, look for the big string of `else if (hostname.includes('yoyodyne.com')) { return new plugins.YoyodynePlugin();`, and add yours in.

In `index.ts`, look for the `export * from './yoyodyne';` lines, and add yours in.

In `manifest.json`, look for the list under "content_scripts" and "matches", with entries like `*://*.yoyodyne.com/*`, and add yours in.

**Adding support for a new site - advice**

Definitely look at the existing plugins to get some ideas on how you can parse the HTML and what each member of `I.Media` should be.  Copying an existing plugin and hacking on it can save valuable time.   :)

When you're writing `getMedia()`, you will find that some sites have HTML that is relatively easy to scrape - for instance, each piece you're looking for might have a well-defined container, like this...

    <div class="title">My nifty art</div>
    <div class="artist">JoeCool</div>

...so all you have to do is look for the *one* `div` with that *one* `class` and you're done.  Don't overlook the `<title>` tag, and any `<meta>` tags that might be in the header - if the site sets those to useful values, it can simplify your parsing a lot.

Sometimes there won't be a good label in the markup, but you can look at the plain text to figure out what you have...

    <div class="info">Title: My nifty art</div>
    <div class="info">Artist: JoeCool</div>

...this is a little more work, because it's easy to get all the `div`s of class `info`, but then you have to hand-parse the strings inside them to get each piece of data.

The most fun is when there are no labels in the markup, AND there can be a variable amount of things with the same tag.  One submission might have...

    <div>Title: My nifty art</div>
    <div>foo</div>
    <div>bar</div>
    <div>baz</div>
    <div>Artist: JoeCool</div>

...and the next might be...

    <div>Title: My nifty art</div>
    <div>Artist: JoeCool</div>

...which is a mess, for you - you have to get every `div` on the page, and then look at its contents.  You also can't cheat by, say, finding the title, and then just assuming that the very next div is always the artist name.

If the HTML has a reasonable amount of structure to it, querySelector() and querySelectorAll() let you easily specify certain elements of the page to grab, with jquery-like syntax.  Using these is often a better idea than hand-parsing the HTML.

If you have found what you want in a particular element of the page, like `<div class="artist"><b>JoeCool</b></div>`, but the text still has HTML markup in it, like `<b>JoeCool</b>`, using .textContent will get rid of the markup for you.  Look at the existing plugins for examples.

Sometimes it helps to count elements *up* from the bottom of the page.  But - often the comment section is at the bottom, and that will introduce a variable amount of stuff between the bottom of the page and the element you are looking for.

When you're trying to nail down the parsing, liberal use of `logger.log()` is your friend.  Its output will show up in the web console in the browser when the plugin runs.  This can tell you how far along you're getting in the page, and what your parsing is pulling out.  It may be helpful to include your plugin name at the beginning of the string, so you can find "your" output. 

For instance, say each submission page on yoyodyne.com has a tag like `<title>Yoyodyne - My nifty art by JoeCool</title>`.  You might do something like this....

    let titleuser = document.title.slice(11);       // cut off "Yoyodyne - "
    logger.log("yoyodyne: title-user", titleuser);  // show what you have so far

    // ' by ' might be part of a title, but hopefully
    // no users have ' by ' in their name.
    let titleend = titleuser.lastIndexOf(' by ');
    let title = titleuser.slice(0, titleend);       // get everything up to " by "
    logger.log("yoyodyne: title", title);           // show what you found

    // Skip ' by ' and extract user
    let userstart = titleend + 4;
    let username = titleuser.slice(userstart);
    logger.log("yoyodyne: user", username);         // show what you found

Once you're happy with how your plugin works, you might remove *some* of the logger.log statements.  They probably cause a small performance hit to the browser, but I have no idea how large this effect is.

`getPageLinkList()` is usually a little simpler to write.  One common technique is to make a distinction between the user's "favorites" page and a more generic "newest submissions" or "one artist's gallery" page, so you can decide whether to sort the list of links or not.  If the user is looking at their own favorites page, they *probably* want Raccoony's "open all in tabs" button to open the submissions *in the order they were favorited*.  If they're looking at a "newest submissions" page, they *probably* want "open all in tabs" *in the order they were uploaded*.

isSubmissionPage() is probably the easiest function to write; most sites just have one URL format for individual submissions.  If the site has a version that's specially formatted for mobile, you might need to look for two different URL formats - like *both* https://example.com/submissions/123456 and https://example.com/m/submissions/123456 .  Or, *both* https://example.com/submissions/123456 and https://m.example.com/submissions/123456 .

Some things to look out for when writing your plugin:

Make sure to look at a variety of submission types.  Often the HTML will be different between an image, an animation or movie, and a story.

Make sure to look at a variety of submission ages.  Often the HTML will be the same, but things like filenames or links may be different on submissions made when the site was first started.  Some sites have gone through a progression like this

    myniftyart.png                                       # original uploader's filename
    yoyodyne-myniftyart.png                              # site name prepended to original
    yoyodyne-123456.png                                  # site name and submission number
    yoyodyne-{9e0c699b-45c8-4570-a155-a47ade489c6e}.png  # site name and GUID
    yoyodyne-🐭🐭💯💯.png                                 # unicode

so if you assume that the filenames are always `yoyodyne-%s.png`, where `%s` is something sane, you will have a bad time on very old or very new submissions.

Some sites allow artists to group their submissions together - like multiple pages of a comic, or multiple images that all show the same character - so that every submission in that group will also have thumbnails or links to the other submissions in that group on the submission page.  However, "one off" submissions won't have those thumbnails or links on their submission pages.  You need to handle both cases.

**Testing your new plugin - advice**

For initial testing, find a couple of pieces of artwork you like and don't mind seeing over and over, because you will. :)

Try to test against a variety of submissions - new ones, old ones, ones with no comments, ones with lots of comments, ones with a description of "sketch for CoolGuy1, lol", ones with an entire novel in the description, ones with lots of tags, ones with no tags, ones with the thumbnail/links-to-related box, ones without that box.  Look for submissions that have "weird" characters in the title or the tags (commas, periods, spaces, dashes, Unicode, etc).  If you find a good set of submissions that meets most of these requirements, bookmark them all in a "Raccoony test" folder in your browser, and use your browser's "open all in tabs" function to open them quickly.

Test against the "new art by people you're watching" page that most sites have.  If the artists you watch/follow don't post very often, it may help to temporarily follow a couple of prolific ones, to help fill up that page.  You might also test against the "all new art" page that most sites have, and the "recently popular art" page that some sites have.

Turn on the "download metadata file" in the Raccoony preferences, and slam that Download button on all the submissions.  This will give you a text file in the same directory as the .jpg/.png/whatever; you'll see, like, `joecool-myniftyart.png` and `joecool-myniftyart.png.txt` .  Read those text files carefully to make sure you're parsing the page correctly.

I (Eupeptic) don't get paid for this, so I pretty much only test on the browser I use every day, which is desktop Firefox.  :)  As far as I know, none of my plugins have melted desktop Chrome or anybody's phone.  If you're feeling really spry, you can test on more of the supported platforms (desktop Firefox, desktop Chrome, mobile Firefox, mobile Chrome).

**Long-term support**

Don't be surprised if sites make changes to their pages over time that end up breaking your plugin.  *Usually* your plugin will work for a year or two before needing changes, but some sites change things around more often.  Sometimes a simple change will make the plugin work again.  If it looks like it will take more work than you are able to support, please let Simon-Tesla know.

**Comment by Simon-Tesla** [comment]
This feels like a good time to start using the Wiki for stuff. Went ahead and created the documentation page here:
https://github.com/Simon-Tesla/RaccoonyWebEx/wiki/Writing-a-new-Site-Plugin
