### ISSUE TITLE
[FurAffinity] Files with long names and/or non-latin characters aren't saved

### ISSUE THREAD

**Issue by Simon-Tesla** [Simon-Tesla/RaccoonyWebEx#45]
**Describe the bug**
Some files with long cyrillic names are not saving (firefox). www furaffinity net/view/33891942/ example of file. Short names are saving but instead of symbols there are hex numbers. 

**To Reproduce**
1. Go to https://www.furaffinity.net/view/33891942/ (warning NSFW link) and click download
2. Note that there's an error

**Expected behavior**
File downloads, at minimum. We should try to handle the multibyte characters as well.

**Comment by Eupeptic1** [comment]
WFM on new FA (as released on 2019-12-31), Firefox Quantum 68.5.0esr, 64-bit, on Linux desktop, with Raccoony 1.2.2, _as modified to fix some other FA bugs_.  The modified version will shortly be submitted as a pull request.  I didn't try it with the vanilla 1.2.2 FA plugin, or with my modified plugin on old FA.

Raccoony saves both the image and the metadata file.

The image file name has a lot of multibyte characters spelled out as hex, but it is a valid PNG image: `1574179223__D0_A7_D0_BE_D1_82_D0_BE__D1_81_D1_82_D1_80_D0_B0_D1_88_D0_BD_D0_BE__D1_80_D0_BE_D0_BC_D0_B0_D0_BD_D1_82_D0_B8_D1_87_D0_BD_D0_BE_D0_B5__D0_BA_D0_BE_D0_BF_D0_B8_D1_8F__D0_BC_D0_B8_D0_BD_D0_B8_by_raventenebris.png`

The metadata file name is the above, with an additional .txt extension.  The url, filename, and sitefilename entries in the JSON have a lot of %-encoding in them, but they seem to be valid URLs.  For instance, the url in the metadata file is https://d.facdn.net/art/raventenebris/1574179223/1574179194.raventenebris_%D0%A7%D0%BE%D1%82%D0%BE_%D1%81%D1%82%D1%80%D0%B0%D1%88%D0%BD%D0%BE_%D1%80%D0%BE%D0%BC%D0%B0%D0%BD%D1%82%D0%B8%D1%87%D0%BD%D0%BE%D0%B5_%D0%BA%D0%BE%D0%BF%D0%B8%D1%8F_%D0%BC%D0%B8%D0%BD%D0%B8.png , but when I actually visit that in my browser, Firefox changes the %-encoded stuff to the Cyrillic characters.

**Comment by Simon-Tesla** [comment]
Looks like this is an issue on Windows presumably due to path length restrictions or something. Fix is to url-decode the filename first.
