### ISSUE TITLE
DA file saving

### ISSUE THREAD

**Issue by Osprey-Hawk** [Simon-Tesla/RaccoonyWebEx#61]
When I use the 1.2.3 version on Deviant Art, it does save to the artist directory, but it ignores the download link (which isn't always an option, admittedly) and only grabs the full size image.  Perhaps a check for the download link before grabbing the image would fix this?

**Comment by Simon-Tesla** [comment]
The download button contains a link that would fail to actually download when I tried to use it for downloading via Raccoony, and I can't see a good way to fix that. Sorry.
