### ISSUE TITLE
[Feature request] Allowing less than 1 second delay for [Delay between tab loads]

### ISSUE THREAD

**Issue by someonenameguy** [Simon-Tesla/RaccoonyWebEx#68]
**Is your feature request related to a problem? Please describe.**
Let's say I am about to download 400 images. It would take 400 seconds to download all of them on 1 second delay. My computer and network is able to handle faster loading and downloading speeds but it wouldn't likely live through 0 second delay loading everything at once.

**Describe the solution you'd like**
Allow half a second delays or 0.3 second delays.

**Comment by Simon-Tesla** [comment]
The reason for the delay is less to do with the abilities of your own computer or network but about being a good citizen when hitting the webserver and ensuring that the extension doesn't overload things (or potentially trigger DoS detection that might get you banned). So, no plans to change this, sorry.
