### ISSUE TITLE
Add Twitter support for single tweets

### ISSUE THREAD

**Issue by lonelymaw** [Simon-Tesla/RaccoonyWebEx#71]
**Is your feature request related to a problem? Please describe.**
Raccoony's feature to automatically organize media from supported websites by author and other categories is great, and it would be very useful to have available on applicable Twitter posts.

**Describe the solution you'd like**
The Raccoony download button is visible on Twitter's single-tweet pages (i.e., twitter.com/{user}/status/{tweet_id}) with compatible media (up to 4 images, one GIF, or one video). When activated, it downloads and stores the media according to the 'Download path' option in the extension settings.

For the provided examples, the placeholders for Twitter downloads are as follows:
**Example tweet URL:** https://twitter.com/exampleAuthor/status/01234
**Example tweet media URL:** https://pbs.twimg.com/media/56789?format=png

**siteName:** twitter
**submissionId:** 01234
**author:** exampleAuthor
**filename:** 56789 (in case of several images, append _0, _1, etc. to each file)
**filenameExt:** 01234.png
**siteFilename:** 56789
**siteFilenameExt:** 56789.png
**extension:** png
**type:** image
**title:** [none]
**domain:** twitter.com

**Describe alternatives you've considered**
Using the right-click context menu to download Twitter images via Raccoony downloads selected media successfully, but it does not include author information, which is a highly useful feature for other supported sites.

**Additional context**
I don't know how this would necessarily work for the dynamically loaded Twitter homepage, so this feature request doesn't include that functionality. Improving the right-click download to include the author in the metadata is one possible route, but that information may not be easy to extrapolate from something like the example tweet media URL above.

**Comment by Simon-Tesla** [comment]
A twitter plugin has been on my todo list for a while. Definitely something I want to tackle at some point.

**Comment by Simon-Tesla** [comment]
Given the absolute shitshow twitter is in right now, I'm not going to invest time in making a twitter plugin, though I'd certainly be fine accepting a contribution for one.
