### ISSUE TITLE
Firefox Install Issue

### ISSUE THREAD

**Issue by Kuroo2021** [Simon-Tesla/RaccoonyWebEx#72]
When I try intall Racconny on Firefox 82.0.2 (64-bit) I get an message, "Firefox has prevented this site from installing an unverified add-on" and it won't install. I get this link saying that add-ons have to signed.

https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox?as=u&utm_source=inproduct

Then I search for ways to turn off signs add-on to just install it at the bottom of the article on how to turn it off but it don't seem to work. I did recall seeing the add-on in the Firefox add-on store but don't see it there anymore. 

https://extensionworkshop.com/documentation/publish/submitting-an-add-on/

I was not sure what to do address on how to install this addon. Thoughts?

**Comment by Simon-Tesla** [comment]
How exactly are you trying to install the addon? You should be using the XPI file from the releases page:
https://github.com/Simon-Tesla/RaccoonyWebEx/releases/download/1.2.3/raccoony_webextension-1.2.3-an+fx.xpi
This XPI is signed and should work for FF 82.0.2. 

At some point I do plan to put Raccoony in the FF addons site, but I haven't quite gotten there yet.

**Comment by Kuroo2021** [comment]
> 
> 
> How exactly are you trying to install the addon? You should be using the XPI file from the releases page:
> https://github.com/Simon-Tesla/RaccoonyWebEx/releases/download/1.2.3/raccoony_webextension-1.2.3-an+fx.xpi
> This XPI is signed and should work for FF 82.0.2.
> 
> At some point I do plan to put Raccoony in the FF addons site, but I haven't quite gotten there yet.

Yup it working! Thanks sorry about that, thanks!

**Comment by Simon-Tesla** [comment]
No prob. I should probably make the install link directly to the xpi file anyway.
