### ISSUE TITLE
Soundcloud audio embeds on Weasyl aren't detected

### ISSUE THREAD

**Issue by Eupeptic1** [Simon-Tesla/RaccoonyWebEx#74]
**Quick version**

Weasyl allows audio submissions that link to Soundcloud.  These submissions embed Soundcloud's player on the Weasyl submission page.  Raccoony doesn't detect anything on submission pages like this; the raccoon head does not appear.

**Steps to reproduce:**

1.  Visit a page on Weasyl with a Soundcloud-hosted audio file, such as https://www.weasyl.com/~kavaeric/submissions/1968215/scarborough-fair .

2.  Look for the raccoon-head icon at the lower left.

Expected result: Icon appears and offers the normal menu items.

Actual result: Nothing happens.

**Other notes**

Weasyl also allows audio files to be directly hosted on Weasyl.  These still work as expected; you get the raccoon head and menu when visiting the submission page.  Example: https://www.weasyl.com/~kavaeric/submissions/1873551/seven-hundred-years-is-a-long-time

**Environment**
Debian 9.13 on amd64/x86_64, desktop
Firefox 78.5.0esr, 64-bit
Raccoony 1.2.3

**Comment by Eupeptic1** [comment]
**Analysis**

When Raccoony runs on a Soundcloud-hosted submission page, the console reports (in part)

`[raccoony] hasMedia null`
`[raccoony] hasPageLinks false`

The page source is a little different for Soundcloud-hosted and Weasyl-hosted.

*Soundcloud-hosted*

There is a `<div id="detail-stage" class="stage">`, with three child divs: `<div id="detail-art">` for the thumbnail, `<div id="detail-embed" class="pad-left pad-right">` for the iframe to Soundcloud, and `<div class="detail-folder-nav clear">` for the next/previous submission links.

*Weasyl-hosted*

There is a `<div id="detail-stage" class="stage">`, with two child divs: `<div id="detail-art">` for the thumbnail *and* the link to the audio file, and `<div class="detail-folder-nav clear">` for the next/previous submission links.

For a Soundcloud-hosted track, the iframe is

`https://w.soundcloud.com/player/?visual=true&url=https%3A%2F%2Fapi.soundcloud.com%2Ftracks%2F[track-id]&show_artwork=true`

where `[track-id]` is numeric.

If we wanted Raccoony to handle this, we'd probably have to extract the track-id from that link, and then see if there's a way to ask Soundcloud for an audio file directly.  This might possibly happen by passing some other parameters to that api.soundcloud.com site.  Or, it might be against Soundcloud's ToS to do it that way, or we'd need an API key, or something.

Weasyl also allows embedding content of various kinds from at least Sketchfab, Vimeo, YouTube, and Google Docs.  Raccoony may also have trouble detecting content embedded from those sites; I haven't tested it.  There might have to be special cases in the Weasyl plugin for any of those that we want to support.

**Comment by Simon-Tesla** [comment]
Soundcloud itself does a few things to make downloading audio difficult; I've only been able to reliably extract audio using youtube_dl, so I'm not optimistic about being able to support soundcloud via plugin.

**Comment by Simon-Tesla** [comment]
I'm going to declare soundcloud-hosted media out of scope for Raccoony. There are other extensions that specifically work for enabling soundcloud downloads and from what I can tell it's not a trivial endeavor.
