### ISSUE TITLE
e621 saves files to "unknown_artist"

### ISSUE THREAD

**Issue by Osprey-Hawk** [Simon-Tesla/RaccoonyWebEx#76]
This has been going on for a while, but files saved on e621 are saved to "unknown_artist" even if an artist is listed.

**Comment by Simon-Tesla** [comment]
dup of #73

**Comment by nlboom** [comment]
> dup of #73
Please, update the addon. I don't know how to compile.
: )

**Comment by Simon-Tesla** [comment]
Sorry, meant to repackage this over the holidays and wasn't able to get to it. Planning a release in the next couple of days.
