### ISSUE TITLE
FurAffinity plugin includes author name in "title" field in metadata

### ISSUE THREAD

**Issue by Eupeptic1** [Simon-Tesla/RaccoonyWebEx#85]
**Description**
The FA plugin is including the author name in the "title" field in the metadata file.  Instead of just seeing `Title: My nifty art`, you see something like `Title: My nifty art by CoolArtist1`, in both the human-readable and JSON sections of the metadata file.

**Steps to reproduce**
1. In Raccoony, turn on metadata file download, either just for FurAffinity or globally.

2. Visit any image on FA that has both a title and an author.  Example, sfw: https://www.furaffinity.net/view/40428437/

3. Note the title and author that FA lists on the page.

4. Mouse over the raccoon head and click "Download".

5. On the local filesystem, navigate to the directory where Raccoony saved the image and the metadata file, and open the metadata file with your favorite text editor or viewer.

6. Look at the `Title:` entry in the human-readable text, and the `"title":` element in the JSON array, in the metadata file.

**Expected result**
Both entries contain solely the title of the artwork.  Example: `A Taste Test...`

**Actual result**
Both entries contain the title, the word "by", and the artist name.  Example: `A Taste Test... by may825`

**Environment**
Raccoony 1.2.4
Firefox 78.7.0esr, 64-bit, desktop
Debian Linux 9.9, amd64/x86_64

**Additional information**
I have a few metadata files for older images from FA, and this seems to have been happening since at least 2/2020.

This doesn't seem to affect any other functionality of Raccoony - just the entries in the metadata file.

**Comment by Eupeptic1** [comment]
**Analysis**
This may not be considered very important.  :D  It just affects the metadata file.

The FA plugin currently has a function called `getTitle()`, which just looks for the meta tag for the OpenGraph "title" property.  If that meta tag is there, it returns the entire content of the tag, without further parsing.

I suspect it's either always been this way - FA always included the author in the "title" OpenGraph tag, and Raccoony just took that as-is - or that FA used to not include the author in that tag, and then changed at some point.

The HTML for an FA image submission page (new UI) currently provides title information in a few different places:

HTML `<title>` tag - title, author, and munged URL for FA
meta OpenGraph "title" - title and author
meta Twitter "title" - title and author, same as OpenGraph
alt property of the main submission img - title only
h2 heading inside `<div class="submission-title">` - title only

I haven't yet checked any submission pages for audio, animations, text/PDF, etc.

If a fix is wanted, the main options are probably 1) pull it out of the OpenGraph tag like now, and then slice off the artist name or 2) pull it out of some other element on the page.

1 is probably more reliable, and less likely to vary between the new and old UI.

2 involves less hand-parsing, but is more likely to break when FA updates their HTML.

**Comment by KamillaPup** [comment]
I too am having this issue in the filename making it so the author name is in the filename twice.

**Comment by Eupeptic1** [comment]
> I too am having this issue in the filename making it so the author name is in the filename twice.

I can reproduce this if I change the downloaded file name setting away from the default.

With the default setting for a downloaded file name of `raccoony/{siteName}/{author}/{submissionId}_{filename}_by_{author}.{extension}`, I don't get the author's name in the filename twice, but that's because the setting doesn't use `{title}`.

If I change that setting to `raccoony/{siteName}/{author}/{submissionId}_{title}_by_{author}.{extension}` - using `{title}` instead of `{filename}` - then I see the problem KamillaPup reported.  If I download https://www.furaffinity.net/view/42222709/ (sfw) with that setting, I get a filename of `42222709_Raptor(colored)_by_DrAslan_by_draslan.jpg`.  I would expect to have `42222709_Raptor(colored)_by_draslan.jpg` instead.

I didn't think about the title parsing affecting the `{title}` option for the file name.  I will work on a patch for this bug in the next couple of days.

**Comment by Eupeptic1** [comment]
Proposed fix here:  https://gist.github.com/Eupeptic1/767c2f126e80cefce36f8db837322980#file-furaffinity-ts-L188

I changed `getTitle()` to use the `alt` attribute of the main submission image.  (Previously it used the OpenGraph 'title' tag.)  That attribute contains just the title, without the author name appended.  The `alt` attribute gets set to the title, even if the image is just a generic icon or an author-provided image for a non-image submission (story, audio, Flash).

I did a manual test on a couple of images and it worked; the 'title' field in the metadata file now contains just the title, and not the title and author.

I also did an automated before-and-after test on several images, stories, audio files, and Flash submissions.  The only differences were in the human-readable `Title:` and JSON `"title"` entries in the metadata files.

**Comment by Eupeptic1** [comment]
I've been dogfooding this change for a little over three weeks and 600 submissions and it seems to do the right thing.

To test, I didn't change the download file name setting.  I turned on metadata for FA downloads and examined both the human-readable and JSON "title" fields in the metadata, and those fields no longer include the name of the FA account that posted it.

Note that some critters on FA will include the author name in the title when they upload the art, and the revised FA plugin makes no attempt to detect that situation or remove anything from the title.  If Commissioner456 sets the title to "Headshot by CoolArtist1", then the revised FA plugin thinks the title is "Headshot by CoolArtist1".  (Before this change, the FA plugin would have thought the title was "Headshot by CoolArtist1 by Commissioner456".)

**Comment by Simon-Tesla** [comment]
Hmm... is it possible to leave the title as-is? I'd really prefer fidelity when getting metadata, even if they've included their own "by whatever" in the title.

**Comment by Eupeptic1** [comment]
I *am* leaving the title as-is...?

FA is appending the author to the title on *some* of the metadata it presents on a submission page, but not all of it.  The patch tells Raccoony to get the title from one of the pieces of metadata where FA *doesn't* append the author.

I think the proposed patch has more fidelity than the previous situation.

### Before the proposed patch:

Situation 1:

`Commissioner456` uploads an artwork and sets the title to `Headshot`.

FA sets the HTML <title> tag to `Headshot by Commissioner456 -- Fur Affinity [dot] net`.
FA sets the OpenGraph and Twitter meta "title" tags to `Headshot by Commissioner456`.
FA sets the alt attribute of the main image, and an h2 inside a class="submission-title" to `Headshot`.

Raccoony reads the title from the OpenGraph meta "title" tag, so he thinks the title is `Headshot by Commissioner456`.

If the user has the metadata file turned on in Raccoony, it has `Headshot by Commissioner456` in both the human-readable and JSON "title" fields.

If the user is using {title} in the Raccoony filename spec, that expands to `Headshot by Commissioner456`.  If they happen to also have {author} in the filename spec - for example, {submissionId}_{title}\_by\_{author}.{extension} - they will get a filename with some redundant information, like `1234567_Headshot_by_Commissioner456_by_Commissioner456.jpg`.

Situation 2:

`Commissioner456` uploads an artwork and sets the title to `Headshot by CoolArtist1`.

FA sets the HTML <title> tag to `Headshot by CoolArtist1 by Commissioner456 -- Fur Affinity [dot] net`.
FA sets the OpenGraph and Twitter meta "title" tags to `Headshot by CoolArtist1 by Commissioner456`.
FA sets the alt attribute of the main image, and an h2 inside a class="submission-title" to `Headshot by CoolArtist1`.

Raccoony reads the title from the OpenGraph meta "title" tag, so he thinks the title is `Headshot by CoolArtist1 by Commissioner456`.

If the user has the metadata file turned on in Raccoony, it has `Headshot by CoolArtist1 by Commissioner456` in both the human-readable and JSON "title" fields.

If the user is using {title} in the Raccoony filename spec, that expands to `Headshot by CoolArtist1 by Commissioner456`.  If they happen to also have {author} in the filename spec - for example, {submissionId}_{title}_by_{author}.{extension} - they will get a filename with some redundant information, like `1234567_Headshot_by_CoolArtist1_by_Commissioner456_by_Commissioner456.jpg`.

### After the proposed patch:

Situation 1:

`Commissioner456` uploads an artwork and sets the title to `Headshot`.

FA sets the HTML <title> tag to `Headshot by Commissioner456 -- Fur Affinity [dot] net`.
FA sets the OpenGraph and Twitter meta "title" tags to `Headshot by Commissioner456`.
FA sets the alt attribute of the main image, and an h2 inside a class="submission-title" to `Headshot`.

Raccoony reads the title from the alt attribute of the main image, so he thinks the title is `Headshot`.

If the user has the metadata file turned on in Raccoony, it has `Headshot` in both the human-readable and JSON "title" fields.

If the user is using {title} in the Raccoony filename spec, that expands to `Headshot`.  If they happen to also have {author} in the filename spec - for example, {submissionId}_{title}\_by\_{author}.{extension} - they will get a filename without redundant information, like `1234567_Headshot_by_Commissioner456.jpg`.

Situation 2:

`Commissioner456` uploads an artwork and sets the title to `Headshot by CoolArtist1`.

FA sets the HTML <title> tag to `Headshot by CoolArtist1 by Commissioner456 -- Fur Affinity [dot] net`.
FA sets the OpenGraph and Twitter meta "title" tags to `Headshot by CoolArtist1 by Commissioner456`.
FA sets the alt attribute of the main image, and an h2 inside a class="submission-title" to `Headshot by CoolArtist1`.

Raccoony reads the title from the alt attribute of the main image, so he thinks the title is `Headshot by CoolArtist1`.

If the user has the metadata file turned on in Raccoony, it has `Headshot by CoolArtist1` in both the human-readable and JSON "title" fields.

If the user is using {title} in the Raccoony filename spec, that expands to `Headshot by CoolArtist1`.  If they happen to also have {author} in the filename spec - for example, {submissionId}_{title}_by_{author}.{extension} - they will get a filename without redundant information, like `1234567_Headshot_by_CoolArtist1_by_Commissioner456.jpg`.

### Conclusion

What I was trying to say in my previous comment is that the proposed patch only backs out the extra information that **FA** adds to the title field.  It does **not** attempt to look any further into what the original uploader set as the title, and strip out strings like 'by CoolArtist1' that the original uploader may have included at the end of the title.

The reason I said that is that I noticed some uploaders like to put the 'by CoolArtist1' at the end of the title when they upload, and I wanted to make clear that the patch does not try to do anything about that situation.

**Comment by Simon-Tesla** [comment]
Okay, so the change is that where before we included the artist name in the title (like FA does by default in its <title> element), we instead use the title as shown in the UI, like so:
![image](https://user-images.githubusercontent.com/2214046/124045370-5c486d80-d9c4-11eb-9936-3b0f501e5241.png)

If this is the case, then that is what I'd expect and this is evidence I shouldn't be responding to these threads within 30 minutes of waking up, sorry about that. :P

**Comment by Eupeptic1** [comment]
> so the change is that where before we included the artist name in the title (like FA does by default in its <title> element), we instead use the title as shown in the UI

Correct!

In the example in your screen shot, stock 1.2.4 would have thought the title was `Interconnection (by Jonas) by TimothyFrisby`.

With the proposed patch, the title would be just `Interconnection (by Jonas)`.

I know it's hard to get a diff from a gist, but the change is in `getTitle()` in the FA plugin.

### As shipped in 1.2.4
    function getTitle(): string {
        let titleElt = querySelector("meta[property='og:title']");
        return titleElt
            ? titleElt.getAttribute('content')
            : '';
    }

### Proposed patch
    // FA includes the author name in the title in several of the metadata
    // fields, so use one that has *just* the title.  As of 2021-06, the alt
    // of the submission image qualifies.
    function getTitle(): string {
        let img = <HTMLImageElement>document.getElementById('submissionImg');
        logger.log("fa: getTitle: img ", img);
    
        let title = img.getAttribute('alt');
        logger.log("fa: getTitle: alt ", title);
    
        return title
            ? title
            : '';
    }

**Comment by Simon-Tesla** [comment]
Sounds good to me then, carry on. Let me know when you're ready to roll this into a pull request.

**Comment by Eupeptic1** [comment]
Pull request is go: https://github.com/Simon-Tesla/RaccoonyWebEx/pull/102

**Comment by Eupeptic1** [comment]
I have written and tested a fix [here](https://gist.github.com/Eupeptic1/fe9c9946223facdac96b41cc810d453c).

I changed `getTitle()` to look for the element that creates the human-readable title - the one that's at the top of the box that the description is in - because that element is present on all types of submissions.  It's named differently on the old and new UIs (`div.submission-title` vs `div.classic-submission-title`), so I check for both.

#### Test - before this change vs after, both on new UI

I tested it by downloading my set of 30 test FA submissions under the new UI (test), and comparing that to the same set of submissions that I downloaded under the new UI back in June, before I tried to fix this issue the first time (reference).  The test and reference runs downloaded the same number and type of files, including the Flash files.  The downloaded images, stories, Flash, etc all compare binary equal.

The downloaded metadata files are almost the same, except for Title field in both the human-readable and JSON text.  The reference run has the titles with the author name appended, and the test run has the titles without the author name appended.

#### Test - after this change, old vs new UI

I also tested by downloading my set of 30 test FA submissions under the old UI (test2), and comparing that to the same set of submissions I downloaded under the new UI (test).  The test and test2 runs downloaded the same number and type of files, including the Flash files.  The downloaded images, stories, Flash, etc all compare binary equal.

The downloaded metadata files are almost the same, except for the url (all submissions) and previewUrl (Flash submissions only) fields, in both the human-readable and JSON formats.  FA's old UI gives URLs with `/download/` in them for non-image submissions, while the new UI does not, and that difference shows up in the metadata files.
