### ISSUE TITLE
Compatibility issue with foxygestures

### ISSUE THREAD

**Issue by Athesis** [Simon-Tesla/RaccoonyWebEx#9]
There is an compatibility issue with https://github.com/marklieberman/foxygestures. If Fullscreen pictures are enabled, gestures can't be made on these pictures.

**Comment by Simon-Tesla** [comment]
I'm not sure this is fixable; in general the security model for extensions prevents them from interacting with each other unless they do some work on both sides to opt-in to some behavior, and even then that generally only allows some limited communication between them. As far as FoxyGestures is concerned, Raccoony's overlay doesn't even exist in the DOM, so it can't interact with Raccoony's UI.

**Comment by Simon-Tesla** [comment]
closing old issues
